### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by sinni800** [snobb/xbright#1]
I get this: 
```
cc -Wall  -std=c99 -pedantic -g -DDEBUG -o obj/xbright.o -c xbright.c
xbright.c: In Funktion »brightUp«:
xbright.c:76:50: Fehler: expected expression before »)« token
     unsigned int newValue = (current+1 < MAXVALUE) ? current+1 : MAXVALUE;
                                                  ^
xbright.c: In Funktion »brightDown«:
xbright.c:90:27: Fehler: expected expression before »)« token
     if (current > MAXVALUE) {
                           ^
xbright.c: In Funktion »brightSet«:
xbright.c:107:47: Fehler: expected expression before »)« token
     if ((setValue < 0) || (setValue > MAXVALUE)) {
                                               ^
xbright.c: In Funktion »usage«:
xbright.c:146:53: Fehler: expected expression before »)« token
     printf("usage: %s [+-=[0-%d]]\n", NAME, MAXVALUE);
                                                     ^
make: *** [Makefile:50: obj/xbright.o] Fehler 1
```

Using ArchLinux on gcc 6.2.1

**Comment by snobb** [comment]
The problem is that the Makefile cannot find the brightness data in `/sys`. ArchLinux is using bleeding edge Linux kernels, so I reckon you may need to change the find command in the Makefile to make it work.

Makefile:
```bash
# Autoconfiguration
BRIGHTNESSFILE=`find /sys/devices/|grep "video0/brightness" | tail -1`
MAXVALUE=`find /sys/devices/ | grep "video0/max_brightness" | tail -1 | xargs tail -1`
```

Please search for the brightness files (eg. `find /sys/devices | grep -i brightness`) and update the Makefile.

It's been a while since I used the program last time. I'll test when I have a chance and update the repo.

**Comment by sinni800** [comment]
Ah, I see. You should look in 

    /sys/class/backlight/*/

nowadays. That's the supported way of today

**Comment by snobb** [comment]
Cool. Thanks for the info. Does it work once the path is changed?

**Comment by sinni800** [comment]
I haven't checked yet, haven't found the time

**Comment by snobb** [comment]
FYI: I've checked on Debian and the old command worked. In any case I've updated the Makefile to use /sys/class/backlight.

**Comment by snobb** [comment]
wasn't really a problem - rather misconfiguration.

**Comment by sinni800** [comment]
Sorry I had a lot to learn for uni in the last days. 

Anyway, /sys/class/backlight is the supported way and works for me. 

Sometimes the backlight is not attached to the display device or video output which is why this is a better way
