### ISSUE TITLE
isn't it supposed to..

### ISSUE THREAD

**Issue by abdulbadii** [snobb/xbright#10]
isn't it supposed to be

install:
   		$(INSTALL) $(INSTALL_ARGS) $(TARGET) $(INSTALL_DIR)
   		@echo "DONE"

instead of

install: release
  		$(INSTALL) $(INSTALL_ARGS) $(TARGET) $(INSTALL_DIR)
  		@echo "DONE"

isn't it too supposed to be different in **make** and debug-inclusive **make**

**Comment by snobb** [comment]
Not sure I get what you mean. Answering your question I believe it isn't.
The `make install` creates a clean release build and installs it. I know conventionally build and install steps are separated but I see no point here.

**Comment by snobb** [comment]
I think I know what you mean and a friend of mine flagged it to me some time ago, but I never had a chance to fix it.
For future - please try to add some valid problem description and a justification for the proposed solution when you open issues. Eg. what is the problem exactly? How your suggested change is better?
It's never helpful to report an issue with some vague rhetorical questions and I for one had an urge to just answer `NO IT ISN'T` and close the issue which would be a very suitable response for an issue with such a problem description.
