### ISSUE TITLE
Fix for intel card

### ISSUE THREAD

**Issue by MelleB** [snobb/xbright#2]
Hi,

Thanks for your work. Came here because xbacklight wasn't working for me. This works great!
I had to adjust values of BRIGHTNESSFILE and MAXVALUE in the Makefile a little to get  it to work for my intel card:

    BRIGHTNESSFILE=/sys/class/backlight/intel_backlight/brightness
    MAXVALUE=`cat /sys/class/backlight/intel_backlight/max_brightness`

I noticed old values for auto configuration were commented out above. In my case it would have worked if these were set to something like `find /sys/class/backlight/*/brightness`.

Best,
Melle

**Comment by snobb** [comment]
I'm glad that it worked for you.
I've updated the Makefile. Thanks for reporting.
