### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by abrahamparayil** [snobb/xbright#6]
I've been using this package for a while now. I would like to package this project for Debian. Hope that's okay with the author. @snobb

**Comment by snobb** [comment]
Thanks, I am glad it’s been useful.
As long as I am mentioned as author, I do not mind at all.
It’s hardware dependent though, so it’s not practical to distribute it in precompiled version. On some laptops the drivers brightness range is 0-255, on others - much smaller. Eg. On my Toshiba it’s 0-7, on Dell Latitude 6410 it’s 0-15.
It would only make sense to package it if I set the upper limit during the runtime, which is trivial. I’ll see to adding that feature.

**Comment by snobb** [comment]
Actually thinking more about it, adding runtime range check will significantly increase the complexity of the tool. There are similar tools (eg. xbacklight) that already do that. The purpose of this tool was to be simpler an so it will remain.
So you have my permission, but frankly I don't see how it would be practical to package it in xbright's present form.

**Comment by snobb** [comment]
This tool was inspired by suckless project where every project is configured via C source code and thus requires recompiling for reconfigure. Difficult as it sounds it really saves a lot of complexity and in this case it only needs to be done once.

**Comment by abrahamparayil** [comment]
I love suckless too. The reason I started using this was because it was easier and more minimal than xblacklight in my opinion. I'd like it to remain that way.

**Comment by abrahamparayil** [comment]
Maybe once you or someone else figure out a way to make this work everywhere. I'll package it.

**Comment by ghost** [comment]
what is the license this program?

**Comment by snobb** [comment]
It's MIT. I've just updated the repo to reflect that.
