### ISSUE TITLE
pedantic code warning: xbright.c:93:5: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’

### ISSUE THREAD

**Issue by allanlaal** [snobb/xbright#8]
allan@L4:/opt/xbright$ make && sudo make install
    cc -Wall -std=c99 -pedantic -g -DDEBUG -o obj/xbright.o -c xbright.c
    cc -g -o xbright obj/xbright.o
    [sudo] password for allan: 
    rm -f *.core
    rm -f build_host.h
    rm -f xbright
    rm -rf ./obj
    cc -Wall -std=c99 -pedantic -Os -o obj/xbright.o -c xbright.c
    xbright.c: In function ‘get_current’:
    xbright.c:93:5: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
       93 |     fscanf(input, "%d", &value);
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc  -o xbright obj/xbright.o
    strip xbright
    install -o root -g root -m 4755   xbright /usr/local/bin/
    DONE

**Comment by snobb** [comment]
What's your gcc version?
Cannot reproduce this warning on my machine.

```
$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ sudo make install clean
rm -f *.core
rm -f build_host.h
rm -f xbright
rm -rf ./obj
cc -Wall -std=c99 -pedantic -Os -o obj/xbright.o -c xbright.c
cc  -o xbright obj/xbright.o
strip xbright
install -o root -g root -m 4755   xbright /usr/local/bin/
DONE
make: Nothing to be done for 'clean'.
```
Also curious that the warning did not trigger during `make`, but did during `make release`.
In any case the warning is benign. I'll add a explicit ignore for the return value though.

**Comment by allanlaal** [comment]
my bad, this was run with gcc 5.x :D 

	  allan@L4:~$ whereis gcc
	  gcc: /usr/bin/gcc /usr/lib/gcc /usr/share/gcc /home/linuxbrew/.linuxbrew/bin/gcc /usr/share/man/man1/gcc.1.gz
	  allan@L4:~$ /usr/bin/gcc --version
	  gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
	  Copyright (C) 2020 Free Software Foundation, Inc.
	  This is free software; see the source for copying conditions.  There is NO
	  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	  
	  allan@L4:~$ gcc --version
	  gcc (Homebrew GCC 5.5.0_7) 5.5.0
	  Copyright (C) 2015 Free Software Foundation, Inc.
	  This is free software; see the source for copying conditions.  There is NO
	  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
	  
	  allan@L4:~$ /home/linuxbrew/.linuxbrew/bin/gcc --version
	  gcc (Homebrew GCC 5.5.0_7) 5.5.0
	  Copyright (C) 2015 Free Software Foundation, Inc.
	  This is free software; see the source for copying conditions.  There is NO
	  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

oops

**Comment by snobb** [comment]
No worries. :)
